export const inputs = [
    {
      id:1,
      name:"reg",
      type:"text",
      placeholder:"Enter Registration Number",
      errorMessage: "Must be a Registration Number",
      pattern: "^[A-Za-z0-9 -_'@]{5,100}$",
      label: "Registration Number",
      required: true,
    },
    {
      id:2,
      name:"stage",
      type:"text",
      placeholder:"stage name",
      errorMessage: "enter at least 5 characters",
      label: "From",
      pattern: "^[A-Za-z0-9 -_'@]{5,100}$",
      required: true,
    },
    {
      id:3,
      name:"to",
      type:"text",
      placeholder:"destination",
      errorMessage: "enter at least 5 characters",
      label: "To",
      pattern: "^[A-Za-z0-9 -_'@]{5,100}$",
      required: true,
    },
    {
      id:4,
      name:"fare",  
      type:"number", 
      placeholder:"Amount in Ksh",
      errorMessage: "enter a valid amount",
      label: "Bus Fare",
      required: true,
    },
    {
        id:5,
        name:"driver",
        type:"text",
        placeholder:"enter driver's name",
        errorMessage: "enter at least 5 characters",
        label: "Driver's Name",
        pattern: "^[A-Za-z0-9 -_'@]{5,100}$",
        required: true,
      },
  ];